In [2]:
from darknet import *
import darknet as dn
import util as util
import pandas as pd

In [8]:
torch.tensor().shape

SyntaxError: invalid syntax (<ipython-input-8-e4d3378a87ac>, line 1)

In [3]:
model = Darknet("../cfg/yolov3.cfg")
model.load_weights("../yolov3.weights")
inp_dim=model.inp_dim
df = pd.read_csv('../annotations.csv')

for index, row in df.iterrows():
    imgpath='../images/images/'+row['filename']+'_img'+row['framespan'].split(':')[0]+'.jpg'
    inp = get_test_input(imgpath)
    target=torch.tensor([[[row['x']/(1920),row['y']/(1080),row['width']/(1920),row['height']/(1080),1,1]]])
    
    break






In [4]:
inp_dim=model.inp_dim
print(target*inp_dim)
target= (target.squeeze(-3))


tensor([[[2.8333e-01, 1.2139e+02, 1.5583e+01, 2.1659e+01, 5.4400e+02,
          5.4400e+02]]])


In [5]:
target=util.xyxy_to_xywh(target) # target in normal scale

inp_dim=model.inp_dim

raw_pred,pw_ph,cx_cy,stride = model(inp, True)
# raw_pred=raw_pred.to(device='cuda')

true_pred=util.transform(raw_pred.clone(),pw_ph,cx_cy,stride)



true_pred=true_pred.squeeze(-3)

iou_mask,noobj_mask=util.get_responsible_masks(true_pred,target*inp_dim)


raw_pred=raw_pred.squeeze(-3)
pw_ph=pw_ph.squeeze(-3)
cx_cy=cx_cy.squeeze(-3)
stride=stride.squeeze(-3)

noobj_box=raw_pred[:,4].clone()
noobj_box=noobj_box[noobj_mask]

raw_pred=raw_pred[iou_mask,:]
pw_ph=pw_ph[iou_mask,:]
cx_cy=cx_cy[iou_mask,:]
stride=stride[iou_mask,:]

target[0,0:4]=target[0,0:4]*(inp_dim/stride)

target=util.transform_groundtruth(target,pw_ph,cx_cy)

RuntimeError: expected device cpu but got device cuda:0

In [1]:
print(raw_pred.shape)
print(noobj_box.shape)

NameError: name 'raw_pred' is not defined

In [9]:
no_obj_conf_loss=0
for no_obj in noobj_box: 
    no_obj_conf_loss =no_obj_conf_loss + (0-no_obj)**2

In [10]:
print(no_obj_conf_loss)

tensor(4346.0645, grad_fn=<AddBackward0>)


In [45]:
print(true_pred[iou_mask,:])

tensor([[  3.9615, 123.9904,  15.1550,  29.6256,   0.4966,   0.4970]],
       grad_fn=<IndexBackward>)


In [16]:
from darknet import *
import darknet as dn
import util as util

model = Darknet("../cfg/yolov3.cfg")
model.load_weights("../yolov3.weights")
inp = get_test_input('../dog-cycle-car.png')
tranf_pred,anchs,grid = model(inp,False)



In [14]:
print(tranf_pred)

tensor([[[4.5092e-06, 1.9475e+01, 1.4379e+02, 9.2864e+01, 2.5936e-06,
          1.5060e-02],
         [9.2512e-02, 1.9531e-01, 5.9632e-01, 8.7011e-01, 5.8082e-04,
          9.6061e-04],
         [9.5038e-02, 2.2195e-02, 6.2958e-01, 1.3883e-01, 7.0117e-04,
          4.9626e-04],
         ...,
         [5.4007e+02, 5.4011e+02, 1.0284e+01, 1.3622e+01, 4.9354e-01,
          4.8176e-01],
         [5.3996e+02, 5.3999e+02, 1.5509e+01, 2.9669e+01, 4.9595e-01,
          4.9371e-01],
         [5.3996e+02, 5.3999e+02, 3.2917e+01, 2.3590e+01, 5.0755e-01,
          5.0578e-01]]], grad_fn=<CatBackward>)


In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

df = pd.read_csv('../annotations.csv')
df.describe()
points=np.array([df['width'],df['height']]).T



kmeans = KMeans(n_clusters=3).fit(points)
print(kmeans.cluster_centers_)



# for index, row in df.iterrows():
    





ModuleNotFoundError: No module named 'sklearn'

torch.Size([1, 1, 2])

In [38]:
import math
math.sqrt(330000)
576*576*576


191102976

In [41]:
target=torch.tensor([[40.0,40.0,1.0,5.9]])
abs_target=util.get_abs_target_coord(target)
abs_pred_box=util.get_abs_pred_coord(pred[0])

box=pred[0]


iou=util.bbox_iou(abs_target,abs_pred_box)
iou_mask=iou.max() == iou

ignore_mask=0.5<iou

final_mask=ignore_mask* iou.max() != iou
noobj_box=box[final_mask,:]



abs_pred_box=pred[0,iou_mask,:]



In [36]:
17*17*3+34*34*3+68*68*3

18207

In [43]:
1%3

1

In [37]:
print(iou_mask[18207])

IndexError: index 18207 is out of bounds for dimension 0 with size 18207

In [42]:
a= ((iou_mask == True).nonzero())
print(a)



tensor([[5370]])


In [2]:
array=np.zeros([80])
ar2=np.array([122,25,91,46,0.2])
ar3=np.array([12,245,16,60,0.1])
ar4=np.array([150,45,7,98,0.8])
ar5=np.array([22,23,70,403,0.1])


ar2=np.concatenate((ar2,array),axis=0)
ar3=np.concatenate((ar3,array),axis=0)
ar4=np.concatenate((ar4,array),axis=0)
ar5=np.concatenate((ar5,array),axis=0)

targets=torch.tensor([[ar2,ar3,ar4,ar5]])
print(targets.shape)

print(targets.shape)
for obj in targets[0]:
    print(obj.shape)



torch.Size([1, 4, 85])
torch.Size([1, 4, 85])
torch.Size([85])
torch.Size([85])
torch.Size([85])
torch.Size([85])


In [ ]:
anchors=3
batch=0
obj=0
target=torch.stack([targets[batch,obj,0:4] for a in range(anchors)])
target=target.type(torch.float)
target=util.get_abs_coord(target)
print(target)

In [ ]:
for i in range(2):
    print(i)

In [4]:
%pylab inline


import os, sys, random
import xml.etree.ElementTree as ET
from glob import glob
import pandas as pd
from shutil import copyfile

annotations = sorted(glob('WOSDETC19/*.xml'))

df = []
cnt = 0
for file in annotations:
    prev_filename = file.split('/')[-1].split('.')[0] + '.jpg'
    filename = str(cnt) + '.jpg'
    row = []
    parsedXML = ET.parse(file)
    for node in parsedXML.getroot().iter('object'):
        blood_cells = node.find('name').text
        xmin = int(node.find('bndbox/xmin').text)
        xmax = int(node.find('bndbox/xmax').text)
        ymin = int(node.find('bndbox/ymin').text)
        ymax = int(node.find('bndbox/ymax').text)
        row = [prev_filename, filename, blood_cells, xmin, xmax,ymin, ymax]
        df.append(row)
    cnt += 1

data = pd.DataFrame(df, columns=['prev_filename', 'filename', 'cell_type','xmin', 'xmax', 'ymin', 'ymax'])

data[['filename', 'cell_type', 'xmin', 'xmax', 'ymin', 'ymax']]

Populating the interactive namespace from numpy and matplotlib


Empty DataFrame
Columns: [filename, cell_type, xmin, xmax, ymin, ymax]
Index: []

In [ ]:
target[0,2:]
target[0,2]

In [5]:
import torch.optim as optim
inp = get_test_input()

pred = model(inp, torch.cuda.is_available())

optimizer = optim.SGD(model.parameters(), lr=0.00001)


loss=util.yolo_loss(pred,targets)
loss.backward()
optimizer.step()



TypeError: get_test_input() missing 1 required positional argument: 'imgpath'

In [ ]:
print(pred)

In [ ]:

import os, sys, random
import xml.etree.ElementTree as ET
from glob import glob
import pandas as pd
from shutil import copyfile

annotations = sorted(glob('WOSDETC19/*.xml'))

df = []
cnt = 0
for file in annotations:
    row=[]
    parsedXML = ET.parse(file)
    root= parsedXML.getroot()
    if (cnt!=1):
        file=file.split('/')[-1].split('.')[0] + '.mp4'
    else:
        file=file.split('/')[-1].split('.')[0] + '.mpg'
    for child in root[1][0]:
        if(child.tag=='{http://lamp.cfar.umd.edu/viper#}object'):
            for obj in child[0]:
                filename=file.split('/')[-1].split('.')[0]
                obj_id=child.attrib['id']
                framespan=obj.attrib['framespan']
                x=int(obj.attrib['x'])
                y=int(obj.attrib['y'])
                width=int(obj.attrib['width'])
                height=int(obj.attrib['height'])
                row = [filename, obj_id, framespan, x, y,width, height]
                df.append(row)
    cnt=cnt+1

data = pd.DataFrame(df, columns=['filename', 'obj_id','framespan','x', 'y', 'width', 'height'])
data.to_csv('annotations.csv')

In [ ]:
print(data.head())

In [ ]:
# import numpy as np
# import cv2
# import pandas as pd
# import os, sys, random
# import xml.etree.ElementTree as ET
# from glob import glob
# import pandas as pd
# from shutil import copyfile

# annotations = sorted(glob('WOSDETC19/*.xml'))
# cnt = 0
# for file in annotations:
#     row=[]
#     parsedXML = ET.parse(file)
#     root= parsedXML.getroot()
#     file=file.split('/')[-1].split('.')[0] + '.mp4'
#     cap = cv2.VideoCapture('WOSDETC19/'+file)
    
#     file_jpg=file.split('/')[-1].split('.')[0]
    
#     success = True
#     while success:
#         for child in root[1][0]:
#             if(child.tag=='{http://lamp.cfar.umd.edu/viper#}object'):
#                 for obj in child[0]:
#                     framespan=obj.attrib['framespan']
#                     count = int(framespan.split(':')[0])
#                     cap.set(cv2.CAP_PROP_POS_FRAMES, count-1)
#                     success, frame = cap.read()
#                     cv2.imwrite("images/"+file_jpg+"_img%d.jpg" % count, frame)     # save frame as JPEG file      
#         success=False
#     cnt=cnt+1



In [20]:
1024/32


32.0

In [16]:
import pandas as pd

df = pd.read_csv('../annotations.csv')
df.corr()



Unnamed: 0    obj_id         x         y     width    height
Unnamed: 0    1.000000 -0.179736  0.386403 -0.297138 -0.324744 -0.309528
obj_id       -0.179736  1.000000 -0.065915  0.102089 -0.050285 -0.007669
x             0.386403 -0.065915  1.000000 -0.375353  0.141238  0.141141
y            -0.297138  0.102089 -0.375353  1.000000 -0.040109 -0.053514
width        -0.324744 -0.050285  0.141238 -0.040109  1.000000  0.978448
height       -0.309528 -0.007669  0.141141 -0.053514  0.978448  1.000000

In [17]:
from darknet import *
import darknet as dn
import util as util
import torch.optim as optim

model = Darknet("../cfg/yolov3.cfg")
model.load_weights("../yolov3.weights")


optimizer = optim.SGD(model.parameters(), lr=0.00001)
optimizer.zero_grad()

batch=1
k=0
cost=0
for index, row in df.iterrows():
#     imgpath='../images/'+row['filename']+'_img'+row['framespan'].split(':')[0]+'.jpg'
#     inp = get_test_input(imgpath)
#     targets=torch.tensor([[[row['x']*(416/1980),row['y']*(416/1080),row['width']*(416/1980),row['height']*(416/1080),1,1]]])
#     pred = model(inp, torch.cuda.is_available())
#     loss=util.yolo_loss(pred,targets)
#     print(loss)
#     loss.backward()
#     optimizer.step()
    
    index=1
    imgpath='../images/'+df['filename'][index]+'_img'+df['framespan'][index].split(':')[0]+'.jpg'
    inp = get_test_input(imgpath)
    targets=torch.tensor([[[df['x'][index]*(416/1980),df['y'][index]*(416/1080),df['width'][index]*(416/1980),df['height'][index]*(416/1080),1,1]]])
    pred = model(inp, torch.cuda.is_available())
    loss=util.yolo_loss(pred,targets)
    print(loss)
    loss.backward()
    optimizer.step()
    
#     cost=cost+loss
#     if(k==batch):
#         print(cost)
#         cost.backward()
#         optimizer.step()
#         cost=0
#         k=0
#     k=k+1
    

   
index=10
imgpath='../images/'+df['filename'][index]+'_img'+df['framespan'][index].split(':')[0]+'.jpg'
inp = get_test_input(imgpath)
targets=torch.tensor([[[df['x'][index]*(416/1980),df['y'][index]*(416/1080),df['width'][index]*(416/1980),df['height'][index]*(416/1080),1,1]]])
pred = model(inp, torch.cuda.is_available())
print(pred)
loss=util.yolo_loss(pred,targets)


/home/konsa15/anaconda3/envs/deeplearning/lib/python3.7/site-packages/torch/nn/functional.py:2494: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))


tensor(518.8747, grad_fn=<AddBackward0>)
tensor(334.6520, grad_fn=<AddBackward0>)
tensor(296.8161, grad_fn=<AddBackward0>)
tensor(288.6065, grad_fn=<AddBackward0>)
tensor(289.0010, grad_fn=<AddBackward0>)
tensor(290.6425, grad_fn=<AddBackward0>)
tensor(292.0215, grad_fn=<AddBackward0>)
tensor(292.9909, grad_fn=<AddBackward0>)
tensor(293.6782, grad_fn=<AddBackward0>)
tensor(294.1308, grad_fn=<AddBackward0>)
tensor(294.4370, grad_fn=<AddBackward0>)
tensor(294.6374, grad_fn=<AddBackward0>)
tensor(294.7421, grad_fn=<AddBackward0>)
tensor(294.7888, grad_fn=<AddBackward0>)
tensor(294.7904, grad_fn=<AddBackward0>)
tensor(294.7456, grad_fn=<AddBackward0>)
tensor(294.6743, grad_fn=<AddBackward0>)
tensor(294.5497, grad_fn=<AddBackward0>)
tensor(294.3137, grad_fn=<AddBackward0>)
tensor(293.8732, grad_fn=<AddBackward0>)
tensor(293.1480, grad_fn=<AddBackward0>)
tensor(291.8376, grad_fn=<AddBackward0>)
tensor(289.2444, grad_fn=<AddBackward0>)
tensor(283.1244, grad_fn=<AddBackward0>)
tensor(275.8295,

KeyboardInterrupt: 

In [5]:
obj=torch.tensor([123.5394, 284.6519,   5.2525,   6.9333,   1.0000,   1.0000])
box=torch.tensor([[9.6000e+01, 2.6563e+02, 4.5147e+01, 5.6191e+01, 2.7485e-04, 1.0556e-02],
        [9.6394e+01, 2.5649e+02, 1.3267e+00, 3.3532e-01, 2.0614e-03, 8.3126e-03],
        [9.6071e+01, 2.5609e+02, 1.1885e+00, 4.8042e-01, 2.5095e-03, 2.6043e-03]])

In [10]:
absolute_box=util.get_abs_coord(box[:,0:4])
mask=get_mask(obj[0:2],13,416,3)

print(absolute_box)

tensor([[ 72.4265, 236.5345, 117.5735, 292.7255],
        [ 94.7306, 255.3223,  96.0574, 255.6577],
        [ 94.4767, 254.8498,  95.6653, 255.3302]])


In [17]:
target_box=torch.stack([obj[0:4] for a in range(3)])
target_box=target_box.type(torch.float)
target_box=get_abs_coord(target_box)

iou=util.bbox_iou(target_box,absolute_box)

iou_mask=iou.max() == iou
box=box[iou_mask,:]
iou_value=iou.max()
print(iou_value)

tensor([0., 0., 0.])
tensor(0.)


In [23]:
print(box[0])

tensor([9.6000e+01, 2.6563e+02, 4.5147e+01, 5.6191e+01, 2.7485e-04, 1.0556e-02])


In [ ]:
tensor(0.0240, grad_fn=<AddBackward0>)



In [5]:
from progressbar import ProgressBar
pbar = ProgressBar()

for x in pbar(range(10)):
    x==x


100% |########################################################################|


In [12]:
import sys
import time

for i in range(100):
    sys.stdout.write('\rProgress is %d' %i)
    sys.stdout.flush()
    time.sleep(1)


Progress is 9

KeyboardInterrupt: 

In [1]:
from darknet import *
import darknet as dn
import util as util
import torch.optim as optim
import pandas as pd
import time
import sys
import timeit



df = pd.read_csv('../annotations.csv')

model = Darknet("../cfg/yolov3.cfg")
model.load_weights("../yolov3.weights")


optimizer = optim.Adam(model.parameters(), lr=0.00001)
optimizer.zero_grad()

batch=1

epochs=20
start = timeit.default_timer()

lock=0
remaining=0
estimated=0
for e in range(epochs):
    prg_counter=0
    print("epoch "+str(e))
    for index, row in df.iterrows():
        imgpath='../images/'+row['filename']+'_img'+row['framespan'].split(':')[0]+'.jpg'
        inp = get_test_input(imgpath)
        targets=torch.tensor([[[row['x']*(416/1980),row['y']*(416/1080),row['width']*(416/1980),row['height']*(416/1080),1,1]]])
        pred = model(inp, torch.cuda.is_available())
        loss=util.yolo_loss(pred,targets)
        loss.backward()
        optimizer.step()
        sys.stdout.write('\rProgress is ' +str(prg_counter/8771*100)+'%' ' loss is: '+ str(loss.item())+' Time remaining is ' +str(estimated/60)+' min')
        sys.stdout.flush()
        prg_counter=prg_counter+1
        if ((prg_counter/8771*100>1)&(lock==0)):
            stop = timeit.default_timer()
            estimated= (stop-start)*99
            dur=stop-start
            start=stop
            lock=1
        if estimated!=0:
            stop = timeit.default_timer()
            dur=stop-start
            start=stop
            estimated=estimated-dur
        
        
            

epoch 0


/home/konsa15/anaconda3/envs/deeplearning/lib/python3.7/site-packages/torch/nn/functional.py:2494: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))


Progress is 0.0% loss is: 281.5664367675781 Time remaining is 0.0 min

KeyboardInterrupt: 

In [8]:
t=time.time()
for x in range(100000000):
    x=x+x
time.time()-t

9.437082052230835

In [16]:
from darknet import *
import darknet as dn
import util as util
import torch.optim as optim
import pandas as pd
import time
import sys
import timeit



df = pd.read_csv('../test_annotations.csv')

net = Darknet("../cfg/yolov3.cfg")

'''
when loading weights from dataparallel model then, you first need to instatiate the dataparallel model 
if you start fresh then first model.load_weights and then make it parallel
'''
try:
    PATH = './darknet.pth'
    weights = torch.load(PATH)
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

    # Assuming that we are on a CUDA machine, this should print a CUDA device:
    print(device)
    net.to(device)

    if torch.cuda.device_count() > 1:
      print("Using ", torch.cuda.device_count(), "GPUs!")
      model = nn.DataParallel(net)

    model.to(device)
    
    
    model.load_state_dict(weights)
    model.eval()
except FileNotFoundError: 
    net.load_weights("../yolov3.weights")
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

    # Assuming that we are on a CUDA machine, this should print a CUDA device:

    print(device)
    net.to(device)
    if torch.cuda.device_count() > 1:
      print("Using ", torch.cuda.device_count(), "GPUs!")
      model = nn.DataParallel(net)

    model.to(device)
    






evaluation_df = pd.DataFrame(columns=['pred_x', 'pred_y', 'pred_w','pred_h','pred_conf','pred_class','true_x','true_y','true_w','true_h','true_conf','true_class'])
epochs=1


for e in range(epochs):
    for index, row in df.iterrows():
        if (row['obj_id']==0)&(row['filename']+'_'+str(row['obj_id'])+'_img'+row['framespan'].split(':')[0]+'.jpg'!='gopro_001_0_img480.jpg'):
            imgpath='../test_images/'+row['filename']+'_'+str(row['obj_id'])+'_img'+row['framespan'].split(':')[0]+'.jpg'
            inp = get_test_input(imgpath)
            targets=torch.tensor([[[row['x']*(416/1920),row['y']*(416/1080),row['width']*(416/1920),row['height']*(416/1080),1,1]]])
            targets=targets.to(device='cuda')
            pred = model(inp, torch.cuda.is_available())
            pred=pred.to(device='cuda')
            pred_mask=pred[0,:,4].max() == pred[0,:,4]
            pred_final=pred[:,pred_mask]
            pred_final=pred_final[0]
            
            abs_gt=util.get_abs_target_coord(targets[0])
            abs_pred=util.get_abs_pred_coord(pred_final)
            if util.bbox_iou(abs_gt, abs_pred).item()>0:
                print(util.bbox_iou(abs_gt, abs_pred).item())
                

            
            
            
            
        


cuda:0
Using  2 GPUs!
0.01647801697254181
0.009011506102979183
0.03468147665262222
0.01256517693400383
0.012057092040777206
0.009695269167423248
0.0059318868443369865
0.008672541938722134
0.005090699531137943
0.01452274713665247
0.02868800424039364
0.0034340033307671547
0.0075789643451571465
0.018371228128671646
0.009470767341554165
0.11426515877246857
0.14587651193141937
0.1941090226173401
0.21469636261463165
0.21769261360168457
0.2082846760749817
0.16980497539043427
0.15823329985141754
0.15460997819900513
0.1609727293252945
0.11344296485185623


In [15]:
32*13



416

In [54]:
dct={'pred_x':pred_final[0,0,0]*1980/416, 'pred_y':pred_final[0,0,1]*1080/416, 'pred_w':pred_final[0,0,2]*1980/416,'pred_h':pred_final[0,0,3]*1080/416,'pred_conf':pred_final[0,0,4],'pred_class':pred_final[0,0,5],'true_x':row['x'],'true_y':'as','true_w':'as','true_h':row['height'],'true_conf':'1','true_class':'1'}

SyntaxError: invalid syntax (<ipython-input-54-044b88d4a380>, line 1)

In [ ]:
evaluation_df = pd.DataFrame(columns=['pred_x', 'pred_y', 'pred_w','pred_h','pred_conf','pred_class','true_x','true_y','true_w','true_h','true_conf','true_class'])