In [1]:
from darknet import *
import darknet as dn
import util as util

In [3]:
model = Darknet("../cfg/yolov3.cfg")
model.load_weights("../yolov3.weights")
inp = get_test_input()
blocks = parse_cfg("../cfg/yolov3.cfg")





TypeError: get_test_input() missing 1 required positional argument: 'imgpath'

In [34]:
2*8771/100


175.42

In [ ]:
pred = model(inp, torch.cuda.is_available())

In [ ]:
print(pred.shape)

In [18]:
416/13


32.0

In [2]:
array=np.zeros([80])
ar2=np.array([122,25,91,46,0.2])
ar3=np.array([12,245,16,60,0.1])
ar4=np.array([150,45,7,98,0.8])
ar5=np.array([22,23,70,403,0.1])


ar2=np.concatenate((ar2,array),axis=0)
ar3=np.concatenate((ar3,array),axis=0)
ar4=np.concatenate((ar4,array),axis=0)
ar5=np.concatenate((ar5,array),axis=0)

targets=torch.tensor([[ar2,ar3,ar4,ar5]])
print(targets.shape)

print(targets.shape)
for obj in targets[0]:
    print(obj.shape)



torch.Size([1, 4, 85])
torch.Size([1, 4, 85])
torch.Size([85])
torch.Size([85])
torch.Size([85])
torch.Size([85])


In [ ]:
anchors=3
batch=0
obj=0
target=torch.stack([targets[batch,obj,0:4] for a in range(anchors)])
target=target.type(torch.float)
target=util.get_abs_coord(target)
print(target)

In [ ]:
for i in range(2):
    print(i)

In [4]:
%pylab inline


import os, sys, random
import xml.etree.ElementTree as ET
from glob import glob
import pandas as pd
from shutil import copyfile

annotations = sorted(glob('WOSDETC19/*.xml'))

df = []
cnt = 0
for file in annotations:
    prev_filename = file.split('/')[-1].split('.')[0] + '.jpg'
    filename = str(cnt) + '.jpg'
    row = []
    parsedXML = ET.parse(file)
    for node in parsedXML.getroot().iter('object'):
        blood_cells = node.find('name').text
        xmin = int(node.find('bndbox/xmin').text)
        xmax = int(node.find('bndbox/xmax').text)
        ymin = int(node.find('bndbox/ymin').text)
        ymax = int(node.find('bndbox/ymax').text)
        row = [prev_filename, filename, blood_cells, xmin, xmax,ymin, ymax]
        df.append(row)
    cnt += 1

data = pd.DataFrame(df, columns=['prev_filename', 'filename', 'cell_type','xmin', 'xmax', 'ymin', 'ymax'])

data[['filename', 'cell_type', 'xmin', 'xmax', 'ymin', 'ymax']]

Populating the interactive namespace from numpy and matplotlib


Empty DataFrame
Columns: [filename, cell_type, xmin, xmax, ymin, ymax]
Index: []

In [ ]:
target[0,2:]
target[0,2]

In [5]:
import torch.optim as optim
inp = get_test_input()

pred = model(inp, torch.cuda.is_available())

optimizer = optim.SGD(model.parameters(), lr=0.00001)


loss=util.yolo_loss(pred,targets)
loss.backward()
optimizer.step()



TypeError: get_test_input() missing 1 required positional argument: 'imgpath'

In [ ]:
print(pred)

In [ ]:

import os, sys, random
import xml.etree.ElementTree as ET
from glob import glob
import pandas as pd
from shutil import copyfile

annotations = sorted(glob('WOSDETC19/*.xml'))

df = []
cnt = 0
for file in annotations:
    row=[]
    parsedXML = ET.parse(file)
    root= parsedXML.getroot()
    if (cnt!=1):
        file=file.split('/')[-1].split('.')[0] + '.mp4'
    else:
        file=file.split('/')[-1].split('.')[0] + '.mpg'
    for child in root[1][0]:
        if(child.tag=='{http://lamp.cfar.umd.edu/viper#}object'):
            for obj in child[0]:
                filename=file.split('/')[-1].split('.')[0]
                obj_id=child.attrib['id']
                framespan=obj.attrib['framespan']
                x=int(obj.attrib['x'])
                y=int(obj.attrib['y'])
                width=int(obj.attrib['width'])
                height=int(obj.attrib['height'])
                row = [filename, obj_id, framespan, x, y,width, height]
                df.append(row)
    cnt=cnt+1

data = pd.DataFrame(df, columns=['filename', 'obj_id','framespan','x', 'y', 'width', 'height'])
data.to_csv('annotations.csv')

In [ ]:
print(data.head())

In [ ]:
# import numpy as np
# import cv2
# import pandas as pd
# import os, sys, random
# import xml.etree.ElementTree as ET
# from glob import glob
# import pandas as pd
# from shutil import copyfile

# annotations = sorted(glob('WOSDETC19/*.xml'))
# cnt = 0
# for file in annotations:
#     row=[]
#     parsedXML = ET.parse(file)
#     root= parsedXML.getroot()
#     file=file.split('/')[-1].split('.')[0] + '.mp4'
#     cap = cv2.VideoCapture('WOSDETC19/'+file)
    
#     file_jpg=file.split('/')[-1].split('.')[0]
    
#     success = True
#     while success:
#         for child in root[1][0]:
#             if(child.tag=='{http://lamp.cfar.umd.edu/viper#}object'):
#                 for obj in child[0]:
#                     framespan=obj.attrib['framespan']
#                     count = int(framespan.split(':')[0])
#                     cap.set(cv2.CAP_PROP_POS_FRAMES, count-1)
#                     success, frame = cap.read()
#                     cv2.imwrite("images/"+file_jpg+"_img%d.jpg" % count, frame)     # save frame as JPEG file      
#         success=False
#     cnt=cnt+1



In [20]:
1024/32


32.0

In [16]:
import pandas as pd

df = pd.read_csv('../annotations.csv')
df.corr()



Unnamed: 0    obj_id         x         y     width    height
Unnamed: 0    1.000000 -0.179736  0.386403 -0.297138 -0.324744 -0.309528
obj_id       -0.179736  1.000000 -0.065915  0.102089 -0.050285 -0.007669
x             0.386403 -0.065915  1.000000 -0.375353  0.141238  0.141141
y            -0.297138  0.102089 -0.375353  1.000000 -0.040109 -0.053514
width        -0.324744 -0.050285  0.141238 -0.040109  1.000000  0.978448
height       -0.309528 -0.007669  0.141141 -0.053514  0.978448  1.000000

In [17]:
from darknet import *
import darknet as dn
import util as util
import torch.optim as optim

model = Darknet("../cfg/yolov3.cfg")
model.load_weights("../yolov3.weights")


optimizer = optim.SGD(model.parameters(), lr=0.00001)
optimizer.zero_grad()

batch=1
k=0
cost=0
for index, row in df.iterrows():
#     imgpath='../images/'+row['filename']+'_img'+row['framespan'].split(':')[0]+'.jpg'
#     inp = get_test_input(imgpath)
#     targets=torch.tensor([[[row['x']*(416/1980),row['y']*(416/1080),row['width']*(416/1980),row['height']*(416/1080),1,1]]])
#     pred = model(inp, torch.cuda.is_available())
#     loss=util.yolo_loss(pred,targets)
#     print(loss)
#     loss.backward()
#     optimizer.step()
    
    index=1
    imgpath='../images/'+df['filename'][index]+'_img'+df['framespan'][index].split(':')[0]+'.jpg'
    inp = get_test_input(imgpath)
    targets=torch.tensor([[[df['x'][index]*(416/1980),df['y'][index]*(416/1080),df['width'][index]*(416/1980),df['height'][index]*(416/1080),1,1]]])
    pred = model(inp, torch.cuda.is_available())
    loss=util.yolo_loss(pred,targets)
    print(loss)
    loss.backward()
    optimizer.step()
    
#     cost=cost+loss
#     if(k==batch):
#         print(cost)
#         cost.backward()
#         optimizer.step()
#         cost=0
#         k=0
#     k=k+1
    

   
index=10
imgpath='../images/'+df['filename'][index]+'_img'+df['framespan'][index].split(':')[0]+'.jpg'
inp = get_test_input(imgpath)
targets=torch.tensor([[[df['x'][index]*(416/1980),df['y'][index]*(416/1080),df['width'][index]*(416/1980),df['height'][index]*(416/1080),1,1]]])
pred = model(inp, torch.cuda.is_available())
print(pred)
loss=util.yolo_loss(pred,targets)


/home/konsa15/anaconda3/envs/deeplearning/lib/python3.7/site-packages/torch/nn/functional.py:2494: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))


tensor(518.8747, grad_fn=<AddBackward0>)
tensor(334.6520, grad_fn=<AddBackward0>)
tensor(296.8161, grad_fn=<AddBackward0>)
tensor(288.6065, grad_fn=<AddBackward0>)
tensor(289.0010, grad_fn=<AddBackward0>)
tensor(290.6425, grad_fn=<AddBackward0>)
tensor(292.0215, grad_fn=<AddBackward0>)
tensor(292.9909, grad_fn=<AddBackward0>)
tensor(293.6782, grad_fn=<AddBackward0>)
tensor(294.1308, grad_fn=<AddBackward0>)
tensor(294.4370, grad_fn=<AddBackward0>)
tensor(294.6374, grad_fn=<AddBackward0>)
tensor(294.7421, grad_fn=<AddBackward0>)
tensor(294.7888, grad_fn=<AddBackward0>)
tensor(294.7904, grad_fn=<AddBackward0>)
tensor(294.7456, grad_fn=<AddBackward0>)
tensor(294.6743, grad_fn=<AddBackward0>)
tensor(294.5497, grad_fn=<AddBackward0>)
tensor(294.3137, grad_fn=<AddBackward0>)
tensor(293.8732, grad_fn=<AddBackward0>)
tensor(293.1480, grad_fn=<AddBackward0>)
tensor(291.8376, grad_fn=<AddBackward0>)
tensor(289.2444, grad_fn=<AddBackward0>)
tensor(283.1244, grad_fn=<AddBackward0>)
tensor(275.8295,

KeyboardInterrupt: 

In [5]:
obj=torch.tensor([123.5394, 284.6519,   5.2525,   6.9333,   1.0000,   1.0000])
box=torch.tensor([[9.6000e+01, 2.6563e+02, 4.5147e+01, 5.6191e+01, 2.7485e-04, 1.0556e-02],
        [9.6394e+01, 2.5649e+02, 1.3267e+00, 3.3532e-01, 2.0614e-03, 8.3126e-03],
        [9.6071e+01, 2.5609e+02, 1.1885e+00, 4.8042e-01, 2.5095e-03, 2.6043e-03]])

In [10]:
absolute_box=util.get_abs_coord(box[:,0:4])
mask=get_mask(obj[0:2],13,416,3)

print(absolute_box)

tensor([[ 72.4265, 236.5345, 117.5735, 292.7255],
        [ 94.7306, 255.3223,  96.0574, 255.6577],
        [ 94.4767, 254.8498,  95.6653, 255.3302]])


In [17]:
target_box=torch.stack([obj[0:4] for a in range(3)])
target_box=target_box.type(torch.float)
target_box=get_abs_coord(target_box)

iou=util.bbox_iou(target_box,absolute_box)

iou_mask=iou.max() == iou
box=box[iou_mask,:]
iou_value=iou.max()
print(iou_value)

tensor([0., 0., 0.])
tensor(0.)


In [23]:
print(box[0])

tensor([9.6000e+01, 2.6563e+02, 4.5147e+01, 5.6191e+01, 2.7485e-04, 1.0556e-02])


In [ ]:
tensor(0.0240, grad_fn=<AddBackward0>)



In [5]:
from progressbar import ProgressBar
pbar = ProgressBar()

for x in pbar(range(10)):
    x==x


100% |########################################################################|


In [12]:
import sys
import time

for i in range(100):
    sys.stdout.write('\rProgress is %d' %i)
    sys.stdout.flush()
    time.sleep(1)


Progress is 9

KeyboardInterrupt: 

In [1]:
from darknet import *
import darknet as dn
import util as util
import torch.optim as optim
import pandas as pd
import time
import sys
import timeit



df = pd.read_csv('../annotations.csv')

model = Darknet("../cfg/yolov3.cfg")
model.load_weights("../yolov3.weights")


optimizer = optim.Adam(model.parameters(), lr=0.00001)
optimizer.zero_grad()

batch=1

epochs=20
start = timeit.default_timer()

lock=0
remaining=0
estimated=0
for e in range(epochs):
    prg_counter=0
    print("epoch "+str(e))
    for index, row in df.iterrows():
        imgpath='../images/'+row['filename']+'_img'+row['framespan'].split(':')[0]+'.jpg'
        inp = get_test_input(imgpath)
        targets=torch.tensor([[[row['x']*(416/1980),row['y']*(416/1080),row['width']*(416/1980),row['height']*(416/1080),1,1]]])
        pred = model(inp, torch.cuda.is_available())
        loss=util.yolo_loss(pred,targets)
        loss.backward()
        optimizer.step()
        sys.stdout.write('\rProgress is ' +str(prg_counter/8771*100)+'%' ' loss is: '+ str(loss.item())+' Time remaining is ' +str(estimated/60)+' min')
        sys.stdout.flush()
        prg_counter=prg_counter+1
        if ((prg_counter/8771*100>1)&(lock==0)):
            stop = timeit.default_timer()
            estimated= (stop-start)*99
            dur=stop-start
            start=stop
            lock=1
        if estimated!=0:
            stop = timeit.default_timer()
            dur=stop-start
            start=stop
            estimated=estimated-dur
        
        
            

epoch 0


/home/konsa15/anaconda3/envs/deeplearning/lib/python3.7/site-packages/torch/nn/functional.py:2494: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))


Progress is 0.0% loss is: 281.5664367675781 Time remaining is 0.0 min

KeyboardInterrupt: 

In [8]:
t=time.time()
for x in range(100000000):
    x=x+x
time.time()-t

9.437082052230835

In [12]:
iou=torch.tensor([1,4,2])
iou_mask=iou.max() == iou
print(iou_mask)
box1=torch.tensor([[1,2,3],[2,2,3],[5,3,5]])
box1=box1[iou_mask,:]
iou_value=iou.max()
print(box1.shape[0])

tensor([False,  True, False])
1
